# Generated by Django 5.1 on 2024-10-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitQ_App', '0005_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='employment_status',
            field=models.CharField(max_length=50),
        ),
    ]
