# Generated by Django 5.1 on 2024-10-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitQ_App', '0006_userdetails_is_profile_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='is_profile_complete',
            field=models.BooleanField(default=True),
        ),
    ]
