# Generated by Django 5.1 on 2024-10-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitQ_App', '0008_alter_userdetails_is_profile_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='is_profile_complete',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='user',
        ),
    ]
