# Generated by Django 5.1 on 2024-10-13 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitQ_App', '0009_remove_userdetails_is_profile_complete_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
