# Generated by Django 5.1 on 2024-10-15 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitQ_App', '0012_wellnesstable_user_alter_wellnesstable_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_trainer',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='trainers_photos/')),
                ('available_for_booking', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to='FitQ_App.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserTrainerRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to='FitQ_App.trainer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_trainers', to='FitQ_App.myuser')),
            ],
        ),
    ]
