# Generated by Django 5.1 on 2024-10-15 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitQ_App', '0012_wellnesstable_user_alter_wellnesstable_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('trainer', 'Trainer')], default='user', max_length=10),
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='trainers_photos/')),
                ('available_for_booking', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to='FitQ_App.myuser')),
            ],
        ),
    ]
