# Generated by Django 5.1 on 2024-10-15 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitQ_App', '0013_myuser_role_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='role',
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_trainer',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserTrainerRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to='FitQ_App.trainer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_trainers', to='FitQ_App.myuser')),
            ],
        ),
    ]
