# Generated by Django 5.1 on 2024-10-31 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitQ_App', '0013_myuser_is_trainer_trainer_usertrainerrelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertrainerrelation',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='usertrainerrelation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_trainer',
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
        migrations.DeleteModel(
            name='UserTrainerRelation',
        ),
    ]
