# Generated by Django 5.1 on 2024-11-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitQ_App', '0015_alter_myuser_password_alter_userdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
